spring.application.name=publisher

server.port=9090

spring.datasource.url=${URL_DB}
spring.datasource.username=${USER_DB}
spring.datasource.password=${PASWD_DB}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret=${JWT_SECRET}
