spring.application.name=consumer

server.port=9091

spring.data.mongodb.url=${MONGO_URL}

logging.level.org.springframework.amqp=DEBUG

#Rabbit Config
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#AMQP Config
amqp.topic.name=loans.topic
amqp.queue.name=loans.queue
