spring.application.name=consumer

server.port=9091

spring.data.mongodb.uri=${MONGO_URL}

spring.datasource.url=${URL_DB}
spring.datasource.username=${USER_DB}
spring.datasource.password=${PASWD_DB}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret=${JWT_SECRET}

#Rabbit Config
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#AMQP Config
amqp.loans.topic.name=loans.topic
amqp.loan.queue.name=loans.queue
amqp.book.queue.name=books.queue

#Logging
logging.group.web=org.springframework.http, org.springframework.web
logging.level.web=DEBUG
logging.file.name=logs/logs-consumer
